version: '3.8'

services:
  postgres-restaurants:
    image: postgres:15-alpine
    container_name: restaurant-db
    environment:
      POSTGRES_DB: ${POSTGRES_RESTAURANT_DB:-restaurant_map_db} 
      POSTGRES_USER: ${POSTGRES_USER1:-matt}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD1:-supersecret}
    ports:
      - "5442:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
    postgres_data:
